matrix:
  include:
  # GCC 9
  - os: linux
    dist: xenial
    sudo: required
    addons: &gcc9
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - pkg-config
        - ninja-build
        - ccache
        - cmake
        - gcc-9
        - g++-9
        - xorg-dev
        - libglu1-mesa-dev
        - libvulkan-dev
        - libopenal-dev
    language: cpp
    cache: ccache
    compiler: gcc
    env:
    - COMPILER=g++-9
    - GSL_CXX_STANDARD=17
    - BUILD_TYPE=Release
    - BUILD_SHARED=ON
    before_install:
    - sudo apt-get update -qq
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90
  # Clang 8
  - os: linux
    dist: xenial
    sudo: required
    addons: &clang8
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-8
        - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
          key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
        packages:
        - pkg-config
        - ninja-build
        - ccache
        - cmake
        - g++-8
        - clang-8
        - xorg-dev
        - libglu1-mesa-dev
        - libvulkan-dev
        - libopenal-dev
    language: cpp
    cache: ccache
    compiler: clang
    env:
    - COMPILER=clang++-8
    - GSL_CXX_STANDARD=17
    - BUILD_TYPE=Release
    - BUILD_SHARED=ON
    before_install:
    - sudo apt-get update -qq
  # XCode 10.2
  - os: osx
    osx_image: xcode10.2
    sudo: required
    addons: 
      homebrew:
        taps:
        - caskroom/cask
        casks:
        - apenngrace/vulkan/vulkan-sdk
        packages:
        - pkg-config
        - ninja
        - ccache
        - cmake
        - gcc
        - llvm
      update: true
    language: cpp
    cache: ccache
    compiler: clang
    env:
    - COMPILER=clang++
    - GSL_CXX_STANDARD=17
    - BUILD_TYPE=Release
    - BUILD_SHARED=OFF
    before_install:
    - export PATH="/usr/local/opt/llvm/bin:/usr/local/opt/ccache/libexec:$PATH"

script:
- git submodule update --init --recursive
- mkdir Build && cd Build
- cmake .. -GNinja -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SHARED_LIBS=$BUILD_SHARED
- ninja
