name: linux_gcc

on: [push, pull_request]

jobs:
  linux_gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Download Dependencies
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update -y
        sudo apt-get install -y build-essential pkg-config cmake ninja-build gcc-10 g++-10 xorg-dev libglu1-mesa-dev libopenal-dev libvulkan-dev
    - name: Build Game
      env:
        CC: gcc-10
        CXX: g++-10
        LD_LIBRARY_PATH: /usr/bin/g++-10/lib
      run: |
        cmake -B Build -GNinja -DCMAKE_BUILD_TYPE=Release
        cmake --build Build